yarnPath: .yarn/releases/yarn-3.2.3.cjs
packageExtensions:
  "@date-io/moment@*":
    dependencies:
      moment: "*"
  react-awesome-query-builder@*:
    dependencies:
      material-ui-confirm: "*"
      "@babel/runtime": "*"
